apiVersion: network.vkcs.upbound.io/v1alpha1
kind: FloatingIP
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/floatingip
  labels:
    testing.upbound.io/example-name: base_fip
  name: base-fip
spec:
  forProvider:
    description: floating ip in external net tf example
    poolSelector:
      matchLabels:
        testing.upbound.io/example-name: example
