apiVersion: network.vkcs.upbound.io/v1alpha1
kind: FloatingIPAssociate
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/floatingipassociate
  labels:
    testing.upbound.io/example-name: floatingip-associate
  name: floatingip-associate
spec:
  forProvider:
    floatingIpSelector:
      matchLabels:
        testing.upbound.io/example-name: base_fip
    portIdSelector:
      matchLabels:
        testing.upbound.io/example-name: persistent_etcd
