apiVersion: networking.crossplane.io/v1alpha1
kind: Router
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/router
  labels:
    testing.upbound.io/example-name: router
  name: router
spec:
  forProvider:
    externalNetworkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vkcs_networking_network
    name: router-tf-example
    tags:
    - tf-example
