apiVersion: networking.crossplane.io/v1alpha1
kind: RouterInterface
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/routerinterface
  labels:
    testing.upbound.io/example-name: app
  name: app
spec:
  forProvider:
    routerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: router
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: app
