apiVersion: networking.crossplane.io/v1alpha1
kind: SubnetRoute
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/subnetroute
  labels:
    testing.upbound.io/example-name: subnet-route-to-external-tf-example
  name: subnet-route-to-external-tf-example
spec:
  forProvider:
    destinationCidr: 10.0.1.0/24
    nextHop: ${vkcs_networking_port.persistent_etcd.all_fixed_ips[0]}
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: app
