apiVersion: networking.crossplane.io/v1alpha1
kind: Floatingip
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/floatingip
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Example Floating IP
    poolRef:
      name: imported-network
    subnetIdRef:
      name: imported-subnet-01