apiVersion: kubernetes.vkcs.upbound.io/v1alpha1
kind: NodeGroup
metadata:
  annotations:
    meta.upbound.io/example-id: kubernetes/v1alpha1/nodegroup
  labels:
    testing.upbound.io/example-name: default_ng
  name: default-ng
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: k8s-cluster
    labels:
    - key: env
      value: test
    - key: disktype
      value: ssd
    maxNodes: 5
    minNodes: 1
    name: default
    nodeCount: 1
    taints:
    - effect: PreferNoSchedule
      key: taintkey1
      value: taintvalue1
    - effect: PreferNoSchedule
      key: taintkey2
      value: taintvalue2
