apiVersion: dns.vkcs.upbound.io/v1alpha1
kind: Zone
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/zone
  labels:
    testing.upbound.io/example-name: zone
  name: zone
spec:
  forProvider:
    adminEmail: admin@example.com
    expire: 3600000
    primaryDns: ns1.mcs.mail.ru
    zone: ${local.zone_name}
