apiVersion: loadbalancer.vkcs.upbound.io/v1alpha1
kind: Listener
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/listener
  labels:
    testing.upbound.io/example-name: app_http
  name: app-http
spec:
  forProvider:
    description: Listener for resources/datasources testing
    loadbalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: app
    name: app-http-tf-example
    protocol: HTTP
    protocolPort: 8080
