apiVersion: loadbalancer.vkcs.upbound.io/v1alpha1
kind: Monitor
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/monitor
  labels:
    testing.upbound.io/example-name: worker_ping_life_checker
  name: worker-ping-life-checker
spec:
  forProvider:
    delay: 20
    maxRetries: 5
    name: worker-ping-life-checker-tf-example
    poolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: http
    timeout: 10
    type: PING
