apiVersion: loadbalancer.vkcs.upbound.io/v1alpha1
kind: Pool
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/pool
  labels:
    testing.upbound.io/example-name: http
  name: http
spec:
  forProvider:
    description: Pool for http member/members testing
    lbMethod: ROUND_ROBIN
    listenerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: app_http
    name: http-tf-example
    protocol: HTTP
